### ISSUE TITLE
There is no difference between software and eip93 test

### ISSUE THREAD

**Issue by liangdonggithub** [vschagen/mtk-eip93#16]
I test software enryption first. Next, I remove eip93 module. And then I test again.
I throught throughput of eip93 will be lower than software's. But they are sames!
log follows:
-----------------------------------------------log split-----------------------------------------------------------
root@openwrt:/# lsmod | grep eip                                                                                                                                         
authenc                 3838  1 crypto_hw_eip93
crypto_hw_eip93        46883  0 
libdes                 18197  2 crypto_hw_eip93,des_generic
root@openwrt:/# openssl speed -elapsed -evp des-cbc                                                                                                                      
You have chosen to measure elapsed time instead of user CPU time.
Doing des-cbc for 3s on 16 size blocks: 1089251 des-cbc's in 3.00s
Doing des-cbc for 3s on 64 size blocks: 306010 des-cbc's in 3.01s
Doing des-cbc for 3s on 256 size blocks: 78893 des-cbc's in 3.00s
Doing des-cbc for 3s on 1024 size blocks: 19877 des-cbc's in 3.01s
Doing des-cbc for 3s on 8192 size blocks: 2490 des-cbc's in 3.00s
Doing des-cbc for 3s on 16384 size blocks: 1244 des-cbc's in 3.00s
OpenSSL 1.1.1l  24 Aug 2021
built on: Tue Aug 31 22:20:08 2021 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: mipsel-openwrt-linux-musl-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
des-cbc           5809.34k     6506.52k     6732.20k     6762.14k     6799.36k     6793.90k
root@openwrt:/# rmmod crypto_hw_eip93                                                                                                                                    
[ 2317.865095] mtk-eip93 1e004000.crypto: EIP93 removed.
root@openwrt:/# openssl speed -elapsed -evp des-cbc                                                                                                                      
You have chosen to measure elapsed time instead of user CPU time.
Doing des-cbc for 3s on 16 size blocks: 1082429 des-cbc's in 3.00s
Doing des-cbc for 3s on 64 size blocks: 303918 des-cbc's in 3.00s
Doing des-cbc for 3s on 256 size blocks: 78522 des-cbc's in 3.01s
Doing des-cbc for 3s on 1024 size blocks: 19779 des-cbc's in 3.00s
Doing des-cbc for 3s on 8192 size blocks: 2483 des-cbc's in 3.01s
Doing des-cbc for 3s on 16384 size blocks: 1241 des-cbc's in 3.00s
OpenSSL 1.1.1l  24 Aug 2021
built on: Tue Aug 31 22:20:08 2021 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: mipsel-openwrt-linux-musl-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
des-cbc           5772.95k     6483.58k     6678.28k     6751.23k     6757.72k     6777.51k
root@openwrt:/# 
---------------------------------------------------log ends-----------------------------------------------
Please help me, thanks!

**Comment by liangdonggithub** [comment]
sorry! clerical error.
I test eip-93 enryption at first. then remove eip-93 module. at last I test again.

**Comment by vschagen** [comment]
That seems to be an issue with the openssl-utils. You need to add -cbc or -ecb after the des or des-ede3 like you would do for aes. Then it works just fine:

Software:

Doing des-cbc for 3s on 16 size blocks: 1082844 des-cbc's in 3.01s
Doing des-cbc for 3s on 64 size blocks: 305911 des-cbc's in 3.01s
Doing des-cbc for 3s on 256 size blocks: 78998 des-cbc's in 3.01s
Doing des-cbc for 3s on 1024 size blocks: 19921 des-cbc's in 3.01s
Doing des-cbc for 3s on 8192 size blocks: 2496 des-cbc's in 3.01s
Doing des-cbc for 3s on 16384 size blocks: 1246 des-cbc's in 3.01s

Doing des-ede3-cbc for 3s on 16 size blocks: 424280 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 64 size blocks: 111277 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 256 size blocks: 28171 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 1024 size blocks: 7064 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 8192 size blocks: 884 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 16384 size blocks: 442 des-ede3-cbc's in 3.01s

Doing aes-128-cbc for 3s on 16 size blocks: 1686449 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 64 size blocks: 524552 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 256 size blocks: 139757 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 1024 size blocks: 35535 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 8192 size blocks: 4462 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 16384 size blocks: 2229 aes-128-cbc's in 3.01s

Doing aes-256-cbc for 3s on 16 size blocks: 1361727 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 64 size blocks: 404496 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 256 size blocks: 106244 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 1024 size blocks: 26887 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 8192 size blocks: 3374 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 16384 size blocks: 1686 aes-256-cbc's in 3.01s

OpenSSL 1.1.1l  24 Aug 2021
built on: Wed Oct 13 20:55:45 2021 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: ccache_cc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
des-cbc           5755.98k     6504.42k     6718.77k     6777.11k     6793.10k     6782.21k
des-ede3-cbc      2255.31k     2366.02k     2395.94k     2403.17k     2405.89k     2405.89k
aes-128-cbc       8994.39k    11153.27k    11886.31k    12088.98k    12143.76k    12132.87k
aes-256-cbc       7238.42k     8600.58k     9036.03k     9146.94k     9182.66k     9177.22k

Hardware EIP93:

root@OpenWrt:~# insmod /tmp/crypto-hw-eip93.ko 
root@OpenWrt:~# openssl speed -elapsed -evp des-cbc
You have chosen to measure elapsed time instead of user CPU time.
Doing des-cbc for 3s on 16 size blocks: 59318 des-cbc's in 3.01s
Doing des-cbc for 3s on 64 size blocks: 58976 des-cbc's in 3.01s
Doing des-cbc for 3s on 256 size blocks: 57263 des-cbc's in 3.01s
Doing des-cbc for 3s on 1024 size blocks: 54342 des-cbc's in 3.01s
Doing des-cbc for 3s on 8192 size blocks: 31069 des-cbc's in 3.01s
Doing des-cbc for 3s on 16384 size blocks: 20466 des-cbc's in 3.01s

Doing des-ede3-cbc for 3s on 16 size blocks: 61675 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 64 size blocks: 63124 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 256 size blocks: 57630 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 1024 size blocks: 49123 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 8192 size blocks: 18358 des-ede3-cbc's in 3.01s
Doing des-ede3-cbc for 3s on 16384 size blocks: 10761 des-ede3-cbc's in 3.01s

Doing aes-128-cbc for 3s on 16 size blocks: 59472 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 64 size blocks: 59419 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 256 size blocks: 62254 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 1024 size blocks: 51646 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 8192 size blocks: 17273 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 16384 size blocks: 9811 aes-128-cbc's in 3.01s

Doing aes-256-cbc for 3s on 16 size blocks: 69781 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 64 size blocks: 69530 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 256 size blocks: 63764 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 1024 size blocks: 45652 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 8192 size blocks: 13523 aes-256-cbc's in 3.01s
Doing aes-256-cbc for 3s on 16384 size blocks: 7551 aes-256-cbc's in 3.01s

OpenSSL 1.1.1l  24 Aug 2021
built on: Wed Oct 13 20:55:45 2021 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: ccache_cc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
des-cbc            315.31k     1253.97k     4870.21k    18487.11k    84557.23k   111400.31k
des-ede3-cbc       327.84k     1342.17k     4901.42k    16711.61k    49963.04k    58574.16k
aes-128-cbc        316.13k     1263.39k     5294.69k    17569.93k    47010.10k    53403.13k
aes-256-cbc        370.93k     1478.38k     5423.12k    15530.78k    36804.12k    41101.52k

Experimental (Using polling vs interrupts):

type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
des-cbc           1550.37k     6042.49k    21848.71k    62401.40k   123590.34k   135513.64k
des-ede3-cbc      1530.59k     5746.29k    18621.24k    41824.79k    62229.26k    64915.48k
aes-128-cbc       1464.29k     5434.03k    17515.59k    39163.07k    57006.52k    59276.33k
aes-256-cbc       1454.64k     5353.48k    15965.47k    31724.27k    42995.75k    44318.45k
